DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS DISCOUNTS;

CREATE TABLE DISCOUNTS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL ,
  PERCENT NUMERIC(13,4) NOT NULL ,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL ,
  PRICE NUMERIC(13,4) NOT NULL ,
  DISCOUNT_ID INTEGER DEFAULT NULL ,
  PRIMARY KEY (ID),
  CONSTRAINT FK_Discount FOREIGN KEY (DISCOUNT_ID) REFERENCES DISCOUNTS (ID)
);